[project]
name = "wstool"
version = "0.2.0"
requires-python = ">=3.8"
dependencies = ["vcstools~=0.1.42", "pyyaml~=6.0.1"]
readme = "README.rst"

[project.scripts]
wstool = "wstool.wstool_cli:wstool_main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
